#ifndef LAYOUT_H
#define LAYOUT_H

#include "class/hid/hid.h"

#define N_COLS 13
#define N_ROWS 5

static const uint8_t layout[N_ROWS][N_COLS] = {
    // TODO: implement fn key, unit8_t layout_fn
    { HID_KEY_CONTROL_LEFT, HID_KEY_NONE, HID_KEY_GUI_LEFT, HID_KEY_ALT_LEFT, HID_KEY_SPACE, HID_KEY_SPACE, HID_KEY_ALT_RIGHT, HID_KEY_ENTER, HID_KEY_BACKSPACE, HID_KEY_BRACKET_LEFT, HID_KEY_BRACKET_RIGHT, HID_KEY_MINUS, HID_KEY_EQUAL },

    { HID_KEY_SHIFT_LEFT, HID_KEY_Z, HID_KEY_X, HID_KEY_C, HID_KEY_V, HID_KEY_B, HID_KEY_N, HID_KEY_M, HID_KEY_COMMA, HID_KEY_PERIOD, HID_KEY_APOSTROPHE, HID_KEY_SLASH, HID_KEY_BACKSLASH },

    { HID_KEY_ESCAPE, HID_KEY_A, HID_KEY_S, HID_KEY_D, HID_KEY_F, HID_KEY_G, HID_KEY_H, HID_KEY_J, HID_KEY_K, HID_KEY_L, HID_KEY_SEMICOLON, HID_KEY_NONE, HID_KEY_NONE },

    { HID_KEY_TAB, HID_KEY_Q, HID_KEY_W, HID_KEY_E, HID_KEY_R, HID_KEY_T, HID_KEY_Y, HID_KEY_U, HID_KEY_I, HID_KEY_O, HID_KEY_P, HID_KEY_NONE, HID_KEY_NONE },

    { HID_KEY_GRAVE, HID_KEY_1, HID_KEY_2, HID_KEY_3, HID_KEY_4, HID_KEY_5, HID_KEY_6, HID_KEY_7, HID_KEY_8, HID_KEY_9, HID_KEY_0, HID_KEY_NONE, HID_KEY_NONE },
};

#endif // LAYOUT_H
